PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX wp:     <http://vocabularies.wikipathways.org/wp#>

SELECT DISTINCT (substr(str(?wikidataRes),32) AS ?wikidata) ?pathwayRes ?title ?organism WHERE {
  ?metabolite a wp:Metabolite ;
    dcterms:isPartOf ?pathwayRes .
  ?pathwayRes dc:title ?title ;
    wp:organismName ?organism ;
    a wp:Pathway .
  ?metabolite wp:bdbWikidata ?wikidataRes .
} ORDER BY ASC(?wikidata) LIMIT 5
