SELECT (substr(str(?compound),32) AS ?wikidata) ?inchikey ?smiles ?chiral WHERE {
  ?compound wdt:P235  ?inchikey .
  OPTIONAL {?compound wdt:P233  ?smiles }
  OPTIONAL {?compound wdt:P2017 ?chiral }
  FILTER (BOUND(?smiles) || BOUND(?chiral))
}
