PREFIX wp:     <http://vocabularies.wikipathways.org/wp#>

SELECT DISTINCT (substr(str(?wikidataRes),32) AS ?wikidata) WHERE {
  ?metabolite a wp:Metabolite ;
    wp:bdbWikidata ?wikidataRes .
} ORDER BY ASC(?wikidata)
